# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RMv4_Recipely' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RMv4_Recipely
	pod "Keychain"

end
